const root=document.getElementById('app');
const localPreview=location.protocol==='file:';
const urlParts=location.pathname.replace(/\/$/,'').split('/');
const lastPart=urlParts.pop();
const rawPath=lastPart==='index.html'?(urlParts.at(-1)||'home'):(lastPart||'home');
const path=['about','press','discography','freelance','contact'].includes(rawPath)?rawPath:'home';
const base=localPreview&&path!=='home'?'../':'./';
const a=localPreview?base+'assets/':'/assets/';
const header=`<header class="topbar"><div class="shell"><a class="brand" href="/">PRODBYGOURD</a><button class="menu-button" aria-expanded="false" aria-controls="nav">MENU ☰</button><nav class="nav" id="nav" aria-label="Main navigation"><a href="/about/">About</a><a href="/press/">Press</a><a href="/discography/">Music</a><a href="https://prodbygourd.lemonsqueezy.com" target="_blank" rel="noopener">Store ↗</a><a href="/freelance/">Freelance</a><a href="/contact/">Contact</a></nav></div></header>`;
const footer=`<footer class="footer"><div class="shell"><div><a class="brand" href="/">PRODBYGOURD</a><small>© ${new Date().getFullYear()} PRODBYGOURD</small></div><div class="footer-links"><a target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=PRODBYGOURD">Apple Music</a><a target="_blank" rel="noopener" href="https://open.spotify.com/search/PRODBYGOURD">Spotify</a><a target="_blank" rel="noopener" href="https://www.youtube.com/results?search_query=PRODBYGOURD">YouTube</a><a target="_blank" rel="noopener" href="https://www.instagram.com/prodbygourd/">Instagram</a><a target="_blank" rel="noopener" href="https://www.tiktok.com/@prodbygourd">TikTok</a></div></div></footer>`;
const form=(service=false)=>`<form class="form" action="https://formsubmit.co/potenzageo23@gmail.com" method="POST"><input type="hidden" name="_subject" value="PRODBYGOURD website ${service?'freelance':'general'} inquiry"><input type="hidden" name="_captcha" value="true"><label>Name<input name="name" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label>${service?`<label>Service<select name="service" required><option value="">Choose a service</option><option>Full song writing / production</option><option>Arrangement / mixing / mastering</option><option>Mixing and mastering</option><option>Custom beat or instrumental</option><option>Sound design</option><option>Engineering</option><option>Other</option></select></label>`:''}<label>Message<textarea name="message" required placeholder="Tell me about your project..."></textarea></label><button class="button dark" type="submit">Send message ↗</button><p class="fine"></p></form>`;
const home=`<main><section class="hero-title"><div class="shell title-grid"><div><span class="eyebrow">Producer • Artist • Sound designer</span><h1 class="display">PRODBYGOURD</h1></div><img class="hero-image" src="${a}hero.webp" alt="PRODBYGOURD in a colorful digital collage"></div></section><section class="section newsletter-section"><div class="shell two-col"><div><span class="eyebrow">Stay in the loop</span><h2>Get the news</h2><p>Join the email list for music updates and announcements.</p></div><div class="panel kit-signup"></div></div></section><section class="hero"><img class="sticker star" src="${a}star.webp" alt=""><img class="sticker player" src="${a}player.webp" alt=""><img class="sticker orb" src="${a}orb.webp" alt=""><div class="shell hero-grid"><div><p>Breaking through the noise of life with electronic tracks, bold production.</p><div class="buttons"><a class="button pink" href="/discography/">Explore the music ↗</a><a class="button" href="/about/">Read more</a><a class="button freelance-cta" href="/freelance/">Hire me: freelance services ↗</a></div></div></div></section><section class="section"><div class="shell two-col"><div><span class="eyebrow">Debut single</span><h2>tokyo club!</h2><p class="intro">A loud, colorful escape from the ordinary. Listen to “tokyo club!” and explore more of the music.</p><div class="buttons"><a class="button" href="https://hypeddit.com/9kny8g" target="_blank" rel="noopener">Listen on streaming ↗</a><a class="button dark" href="/discography/">Discography</a></div></div><video class="cover" autoplay muted loop playsinline preload="metadata" poster="${a}cover.webp" aria-label="Animated tokyo club cover"><source src="${a}tokyo-club-cover.mp4" type="video/mp4"><img src="${a}cover.webp" alt="tokyo club cover art"></video></div></section><section class="section"><div class="shell two-col"><div class="panel"><h2>About PRODBYGOURD</h2><p>Breaking through the noise of life, PRODBYGOURD, delivers a maximalist distraction for those seeking one through his stimulating tracks. Though house and EDM are his specialty, the Nashville-based freelance songwriter and producer explores many different genres for each client. PRODBYGOURD is “…[a]lways a joy to work with. ” said Vicky Gao after recording her 3rd studio single, “natural light” produced, arranged, and engineered by GOURD. PRODBYGOURD is set to release his first studio EP entitled “Club Potential” by the end of 2027.</p><a class="button" href="/about/">Read more ↗</a></div><img class="portrait" src="${a}about-blue.webp" alt="Stylized blue portrait showing two images of PRODBYGOURD"></div></section><section class="section" id="get-in-touch"><div class="shell two-col"><div><span class="eyebrow">Say hello</span><h2>Get in touch</h2><p>Questions, collaborations, or just want to say hi? Send a note.</p><p class="notice">PLEASE USE THE <a href="/freelance/">FREELANCE</a> FORM FOR COMMISSION SERVICES.</p></div><div class="panel">${form()}</div></div></section></main>`;
const about=`<main class="shell page-top"><span class="eyebrow">The artist</span><h1 class="page-title">About</h1><div class="two-col"><div class="panel"><p>Breaking through the noise of life, PRODBYGOURD delivers a maximalist distraction for those seeking one through his electronic tracks. Though influenced by the likes of Ninajirachi and Daft Punk, PRODBYGOURD produces a wide range of genres for his uniquely clients.</p><p>Hailing from Boston, Massachusetts, PRODBYGOURD started to develop his musical abilities at a young age. Infatuated with music contained in the 2 Animusic DVDs his father gave to him, PRODBYGOURD started to create musical tracks on his family computer using Apple’s GarageBand and continued to develop his technical abilities in high school. Throughout his time in the Honors college at Belmont University, GOURD developed his musical prowess mastering classical voice, music theory, composition, orchestration, and arranging. Along the way, he also developed skills in engineering, sound design, the recording arts, landing him a Stage-Hand position at Gnome Recording Studios in Nashville, TN.</p><p>Offering freelance services since 2023, PRODBYGOURD has produced a wide range of tracks. Most notably, in 2024, he arranged and produced “natural light” with the indie pop artist, Vicky Gao. PRODBYGOURD is “…[a]lways a joy to work with. He always sees my vision clearly and executes it precisely,” said Vicky Gao at the April release party.</p><p>PRODBYGOURD is currently working on his first studio EP entitled “Club Potential.” Throughout his life, GOURD at times felt as if his days were blending together. Life felt mundane and boring. This EP is an in-your-face, loud, and eccentric release from this boredom.</p></div><img class="portrait" src="${a}about-blue.webp" alt="Stylized blue portrait showing two images of PRODBYGOURD"></div></main>`;
const press=`<main class="shell page-top press-page"><span class="eyebrow">Electronic press kit</span><h1 class="page-title">PRODBYGOURD</h1><p class="intro epk-tagline">Songwriter • Producer • Sound designer</p><p><a class="button dark" href="${a}EPK.pdf" download="PRODBYGOURD-Brandbook.pdf">Download Brandbook (PDF) ↓</a></p>
<section class="epk-block" id="artist-bio"><span class="eyebrow">The artist</span><h2>Artist bio</h2><div class="two-col epk-bios"><div class="panel"><h3>Short bio</h3><p>Breaking through the noise of life, PRODBYGOURD delivers a maximalist distraction through stimulating electronic tracks. A Nashville-based songwriter and producer specializing in house and EDM, he also explores many genres for each client. His first EP, “Club Potential,” is planned for release by the end of 2027.</p><a class="button" href="${a}PRODBYGOURD-short-bio.txt" download>Download short bio ↓</a></div><div class="panel"><h3>Long bio</h3><p>Breaking through the noise of life, PRODBYGOURD delivers a maximalist distraction for those seeking one through his electronic tracks. Though influenced by the likes of Ninajirachi and Daft Punk, PRODBYGOURD produces a wide range of genres for his uniquely clients.</p><p>Hailing from Boston, Massachusetts, PRODBYGOURD started to develop his musical abilities at a young age. Infatuated with music contained in the 2 Animusic DVDs his father gave to him, PRODBYGOURD started to create musical tracks on his family computer using Apple’s GarageBand and continued to develop his technical abilities in high school. Throughout his time in the Honors college at Belmont University, GOURD developed his musical prowess mastering classical voice, music theory, composition, orchestration, and arranging. Along the way, he also developed skills in engineering, sound design, the recording arts, landing him a Stage-Hand position at Gnome Recording Studios in Nashville, TN.</p><p>Offering freelance services since 2023, PRODBYGOURD has produced a wide range of tracks. Most notably, in 2024, he arranged and produced “natural light” with the indie pop artist, Vicky Gao. PRODBYGOURD is “…[a]lways a joy to work with. He always sees my vision clearly and executes it precisely,” said Vicky Gao at the April release party.</p><p>PRODBYGOURD is currently working on his first studio EP entitled “Club Potential.” Throughout his life, GOURD at times felt as if his days were blending together. Life felt mundane and boring. This EP is an in-your-face, loud, and eccentric release from this boredom.</p><a class="button" href="${a}PRODBYGOURD-long-bio.txt" download>Download full bio ↓</a></div></div></section>
<section class="epk-block"><span class="eyebrow">Listen here</span><h2>Featured music</h2><div class="track-list"><article class="track"><h3>tokyo club! by PRODBYGOURD</h3><audio controls preload="none" controlslist="nodownload noplaybackrate" src="${a}tokyo-club.mp3">Your browser does not support audio playback.</audio><div class="credit"><strong>My role:</strong> Wrote and produced</div></article><article class="track"><h3>CRY ABOUT IT! (feat. Coco Jamar) by PRODBYGOURD</h3><audio controls preload="none" controlslist="nodownload noplaybackrate" src="${a}cry-about-it.mp3">Your browser does not support audio playback.</audio><div class="credit"><strong>My role:</strong> Arranged and produced</div></article></div></section>
<section class="epk-block"><span class="eyebrow">Watch</span><h2>Videos</h2><iframe class="video" src="https://www.youtube-nocookie.com/embed/Ue-fbU2jkz0" title="PRODBYGOURD portfolio video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><p><a class="button" href="/freelance/">Contact for production services ↗</a></p></section>
<section class="epk-block" id="photo-gallery"><span class="eyebrow">Press photos</span><h2>Photo gallery</h2><p>Download high-resolution promotional images for press use.</p><div class="gallery">${[['press-studio.jpg','Studio portrait'],['press-blue-collage.png','Blue collage portrait'],['press-disc-collage.png','Disc collage portrait'],['press-digital-portrait.png','Digital portrait'],['press-digital-alt.jpg','Digital portrait alternate']].map(([file,label])=>`<figure><img src="${a}${file}" alt="${label}" loading="lazy"><figcaption><a class="button" href="${a}${file}" download="PRODBYGOURD-${file}" aria-label="Download ${label}">Download photo ↓</a></figcaption></figure>`).join('')}</div></section>
<section class="epk-block" id="epk-contact"><span class="eyebrow">Booking and press</span><h2>Contact PRODBYGOURD</h2><div class="two-col"><div><p>For production, writing, sound design, mixing, mastering, arranging, press, and booking inquiries.</p><p><a href="mailto:potenzageo23@gmail.com">potenzageo23@gmail.com</a></p><p><a class="button pink" href="/freelance/">Freelance services & quotes ↗</a></p><div class="epk-socials"><a href="https://www.instagram.com/prodbygourd/" target="_blank" rel="noopener">Instagram ↗</a><a href="https://www.tiktok.com/@prodbygourd" target="_blank" rel="noopener">TikTok ↗</a><a href="https://www.youtube.com/results?search_query=PRODBYGOURD" target="_blank" rel="noopener">YouTube ↗</a><a href="https://open.spotify.com/search/PRODBYGOURD" target="_blank" rel="noopener">Spotify ↗</a><a href="https://music.apple.com/us/search?term=PRODBYGOURD" target="_blank" rel="noopener">Apple Music ↗</a></div></div><div class="panel">${form()}</div></div></section></main>`;
const tracks=[['Beat Example 1','Wrote and produced','beat-example-1'],['Beat Example 2','Wrote and produced','beat-example-2'],['Cry About It! (feat. Coco Jamar) by PRODBYGOURD','Arranged and produced','cry-about-it'],['love song no. 4 by callista','Wrote and produced','love-song-no-4'],['tokyo club! by PRODBYGOURD','Wrote and produced','tokyo-club']];
const discography=`<main class="shell page-top"><span class="eyebrow">Selected work</span><h1 class="page-title">Discography</h1><p class="intro">Press play to hear selected productions and collaborations.</p><div class="track-list">${tracks.map(([title,credit,file],i)=>`<article class="track"><span class="tag">Track ${String(i+1).padStart(2,'0')}</span><h3>${title}</h3><audio controls preload="none" controlslist="nodownload noplaybackrate" src="${a}${file}.mp3">Your browser does not support audio playback.</audio><div class="credit"><strong>My role:</strong> ${credit}</div></article>`).join('')}<article class="track"><span class="tag">Track 06</span><h3>natural light by Vicky Gao</h3><audio controls preload="none" controlslist="nodownload noplaybackrate" src="https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/61/ec/71/61ec7185-d621-14b6-162b-c7281374cfff/mzaf_17531319194752173686.plus.aac.p.m4a">Your browser does not support audio playback.</audio><div class="credit"><strong>My role:</strong> Arranged and produced</div></article></div><hr class="divider"><span class="eyebrow">Video work</span><h2 class="page-title">Videos</h2><iframe class="video" src="https://www.youtube-nocookie.com/embed/Ue-fbU2jkz0" title="PRODBYGOURD portfolio video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe><p><a class="button" href="/freelance/">Contact for production services ↗</a></p></main>`;
const freelance=`<main class="shell page-top"><span class="eyebrow">Let's work</span><h1 class="page-title">Freelance</h1><div class="two-col" style="align-items:start"><div class="panel"><p>Contact for production, writing, sound design, mixing and mastering, and arranging quotes and services.</p><h2>Rough quotes</h2><ol class="quote-list"><li>Full song writing, arranging, producing, mixing and mastering: <strong>$800 plus a negotiated percentage of royalties.</strong></li><li>Arranging an existing song, mixing and mastering: <strong>$600 plus a negotiated percentage of royalties.</strong></li><li>Mixing and mastering, with the possibility of a few other instruments or effects: <strong>$350–$400, with no royalties.</strong></li><li>Custom or catalog beats and instrumentals are priced individually.</li></ol><p><strong>Engineering: $15 per hour.</strong></p><p><a class="button" href="/press/#photo-gallery">View and download press photos ↗</a></p></div><div class="panel"><h2>Tell me about it</h2>${form(true)}</div></div></main>`;
const contact=`<main class="shell page-top contact-page"><span class="eyebrow">Say hello</span><h1 class="page-title">Contact</h1><div class="two-col"><div><p class="intro">For production, writing, sound design, mixing, mastering, or arranging, use the freelance form so I know what you need.</p><a class="button pink freelance-cta" href="/freelance/">FREELANCE SERVICES & QUOTES ↗</a><p class="intro">For other questions, send a message here.</p></div><div class="panel">${form()}</div></div></main>`;
const pages={home,about,press,discography,freelance,contact};root.innerHTML=header+(pages[path]||home)+footer;if(localPreview){document.querySelectorAll('a[href^="/"]').forEach(link=>{const target=link.getAttribute('href');link.href=target==='/'?base+'index.html':base+target.replace(/^\//,'').replace(/\/$/,'')+'/index.html'})}document.title=`${path==='home'?'Home':path[0].toUpperCase()+path.slice(1)} | PRODBYGOURD`;const menu=document.querySelector('.menu-button');menu.addEventListener('click',()=>{const open=document.querySelector('.nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});document.querySelectorAll('audio').forEach(player=>player.addEventListener('play',()=>document.querySelectorAll('audio').forEach(other=>{if(other!==player)other.pause()})));

if(path==='home'){const kitBox=document.querySelector('.kit-signup');const addEmail=()=>{const form=kitBox.querySelector('form.formkit-form');if(!form||form.querySelector('input[name="email_address"]'))return;const fields=form.querySelector('.formkit-fields')||form;const input=document.createElement('input');input.type='email';input.name='email_address';input.placeholder='Your email address';input.autocomplete='email';input.required=true;input.className='formkit-input newsletter-email';input.setAttribute('aria-label','Email address');const wrap=document.createElement('div');wrap.className='newsletter-field';wrap.append(input);fields.prepend(wrap)};const observer=new MutationObserver(addEmail);observer.observe(kitBox,{childList:true,subtree:true});addEmail();const kit=document.createElement('script');kit.async=true;kit.dataset.uid='93e6131007';kit.src='https://prodbygourd.kit.com/93e6131007/index.js';kitBox.append(kit)}const iconNames=['star','player','orb','disc','cassette','star','player','orb','disc','cassette','orb','star','disc','player','cassette','star','orb','disc','player','cassette'];document.querySelectorAll('main > section,main.shell').forEach((section,sectionIndex)=>{const layer=document.createElement('div');layer.className='collage-layer';iconNames.forEach((name,i)=>{const img=document.createElement('img');img.src=`${a}${name}.webp`;img.alt='';img.loading='lazy';img.className='collage-piece';img.style.left=`${[3,87,42,75,14,56,4,93,35,68,23,82,8,62,45,94,27,71,12,88][i]}%`;img.style.top=`${[3,7,11,17,22,28,34,38,43,49,55,59,65,70,74,79,83,87,92,96][i]}%`;img.style.transform=`rotate(${(i*37+sectionIndex*19)%70-35}deg)`;layer.appendChild(img)});section.prepend(layer)});

// Move collage icons gently as each section crosses the viewport.
if (!window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
  const sections = [...document.querySelectorAll('.collage-layer')].map(layer => ({
    section: layer.parentElement,
    icons: [...layer.querySelectorAll('.collage-piece')]
  }));
  let pending = false;
  function animateCollage() {
    const viewHeight = window.innerHeight;
    const travel = window.innerWidth < 700 ? 12 : 36;
    sections.forEach(({ section, icons }, sectionIndex) => {
      const box = section.getBoundingClientRect();
      if (box.bottom < 0 || box.top > viewHeight) return;
      const offset = (box.top + box.height / 2 - viewHeight / 2) / viewHeight;
      icons.forEach((icon, index) => {
        const spin = (index * 37 + sectionIndex * 19) % 70 - 35;
        const direction = index % 2 ? 1 : -1;
        icon.style.transform = `translate3d(0, ${offset * travel * direction}px, 0) rotate(${spin}deg)`;
      });
    });
    pending = false;
  }
  function requestCollageFrame() {
    if (!pending) { pending = true; requestAnimationFrame(animateCollage); }
  }
  addEventListener('scroll', requestCollageFrame, { passive: true });
  addEventListener('resize', requestCollageFrame);
  animateCollage();
}
